import type { AppCurrencyCode } from "@/constants/currency";
import { DEFAULT_APP_CURRENCY } from "@/constants/currency";
import type { IntegrationSettings, MockTicketPriority } from "@/constants/integrationSettings";
import { mockPriorityFromRoadmap } from "@/constants/integrationSettings";
import {
  buildDashboardMetrics,
  formatCurrency,
  formatHours,
} from "@/lib/frictionCalculations";
import { formatRelatedReportLine, generateRoadmapItems } from "@/lib/roadmap";
import type { DerivedRoadmapItem, FrictionReport } from "@/types";

function dashboardUrl(): string {
  if (typeof window !== "undefined" && window.location?.origin) {
    return `${window.location.origin}${window.location.pathname || "/"}`;
  }
  return "https://your-frictionmap.example/overview";
}

/**
 * Plain-text Slack-style update for demos (no API calls).
 */
export function buildSlackSummaryMessage(
  reports: FrictionReport[],
  hourlyRate: number,
  settings: IntegrationSettings,
  currency: AppCurrencyCode = DEFAULT_APP_CURRENCY,
): string {
  if (!reports.length) {
    return "FrictionMap: no friction reports yet. Add reports in the app to generate a summary.";
  }
  const metrics = buildDashboardMetrics(reports, hourlyRate);
  const roadmap = generateRoadmapItems(reports, hourlyRate, currency);
  const top = roadmap[0];
  const hours = Math.round(metrics.monthlyHoursLost);
  const topCat = metrics.topCategory ?? "mixed categories";
  let msg = `FrictionMap summary\n`;
  msg += `• Monthly workflow drag: about ${formatHours(hours)} across ${metrics.reportCount} report${metrics.reportCount === 1 ? "" : "s"}.\n`;
  if (settings.slackIncludeCostEstimates) {
    msg += `• Estimated monthly cost leakage: ~${formatCurrency(metrics.monthlyCostLost, currency)} (directional, based on your hourly rate).\n`;
  }
  msg += `• Largest category by time: ${topCat}.\n`;
  if (top) {
    msg += `• Top bottleneck: ${top.problemTitle} (${top.process}).\n`;
    msg += `• Recommended fix: ${top.suggestedFix.split("•")[0]!.trim().slice(0, 220)}${top.suggestedFix.length > 220 ? "…" : ""}\n`;
  } else {
    msg += `• Top bottleneck: (clustering will appear as more reports arrive).\n`;
  }
  msg += `\nOpen FrictionMap: ${dashboardUrl()}`;
  return msg;
}

function acceptanceCriteria(): string {
  return [
    "- Measurable reduction in wait time or rework for this workflow path.",
    "- Owner assigned; success metric tracked for 4 weeks.",
    "- Related friction reports updated when the fix ships.",
  ].join("\n");
}

function ticketTitle(item: DerivedRoadmapItem, system: "jira" | "linear"): string {
  const prefix = system === "linear" ? "[Friction]" : "[FrictionMap]";
  return `${prefix} ${item.problemTitle}`.slice(0, 120);
}

/**
 * Markdown body suitable for Jira description or Linear issue (mock).
 */
export function buildTrackerTicketMarkdown(
  item: DerivedRoadmapItem,
  hourlyRate: number,
  settings: IntegrationSettings,
  system: "jira" | "linear",
  currency: AppCurrencyCode = DEFAULT_APP_CURRENCY,
): { title: string; body: string; priority: MockTicketPriority } {
  const priority = mockPriorityFromRoadmap(item.priorityLevel, settings.defaultTicketPriority);
  const title = ticketTitle(item, system);
  const lines: string[] = [
    `## Problem`,
    item.problem,
    ``,
    `## Impact (estimated)`,
    `- Monthly hours (cluster): ${formatHours(item.monthlyHours)}`,
    `- Monthly cost (cluster): ~${formatCurrency(Math.round(item.monthlyCost), currency)}`,
    `- Annualized (rough): ~${formatCurrency(Math.round(item.annualCost), currency)}`,
    `- Roadmap rank: ${item.priorityLevel} · Recommendation confidence: ${item.recommendationConfidence}`,
    `- Tracker priority (mock): ${priority} — integration default in settings: ${settings.defaultTicketPriority}`,
    ``,
    `## Suggested fix`,
    item.suggestedFix,
    ``,
    `## First step`,
    item.firstStep,
    ``,
    `## Acceptance criteria`,
    acceptanceCriteria(),
  ];

  if (settings.ticketIncludeRelatedReports && item.relatedReports.length) {
    lines.push(``, `## Related reports`, ...item.relatedReports.map((r) => `- ${formatRelatedReportLine(r, hourlyRate, currency)}`));
  }

  lines.push(``, `---`, `_Generated by FrictionMap (${system} export mock — not connected to a live API)._`);

  return { title, body: lines.join("\n"), priority };
}

/** Plain-text title + body for live Jira/Linear APIs (mock footer stripped). */
export function buildTrackerTicketPlainForApi(
  item: DerivedRoadmapItem,
  hourlyRate: number,
  settings: IntegrationSettings,
  system: "jira" | "linear",
  currency: AppCurrencyCode = DEFAULT_APP_CURRENCY,
): { summary: string; description: string } {
  const md = buildTrackerTicketMarkdown(item, hourlyRate, settings, system, currency);
  const body = md.body.replace(/\n\n---\n[\s\S]*$/, "");
  const description = [
    `FrictionMap · Live export · ${system}`,
    `Roadmap: ${item.priorityLevel} · Context: ${md.priority}`,
    "",
    body,
  ].join("\n");
  return { summary: md.title.slice(0, 255), description };
}
